### ISSUE TITLE
Not loading in Sketch 72

### ISSUE THREAD

**Issue by robdell** [Saint-loup/data-from-clipboard#5]
The plugin is not loading in the "Insert > Data" nor "Layer > Data" menus in Sketch 72.1 (124357).
This plugin saves me a shit-ton of time. It's way better than other data populator plugins.
Please fix!!! 🙏🙏🙏

-rob
<img width="724" alt="data" src="https://user-images.githubusercontent.com/37341661/118181053-eaf53100-b3fc-11eb-8c8f-fafa675efc81.png">

**Comment by baptiste-roullin** [comment]
Hi, 

I'm sorry for the problem. It works for me, both by updating Sketch with the plugin already installed, and by doing a fresh install of the plugin. Can you provide more details? What's your Mac OS version, from which Sketch version did you upgrade, did you notice the disappearance at a specific moment (like after reloading Sketch)... ?

There are been a bunch of recent data-related changes in Sketch for plugins, but it should not impact the basic functioning of this one.
