### ISSUE TITLE
Not working in Sketch 87.1

### ISSUE THREAD

**Issue by edclark94** [Saint-loup/data-from-clipboard#6]
I loved this plugin when it was working. Constantly copying table data into table cells that were created as symbols. Now, when using the plugin in the last few versions of Sketch, it doesn't paste into overrides. Would be really amazing if this  was fixed and working again

**Comment by baptiste-roullin** [comment]
Hi, 

Sorry about that. 

To be frank I no longer use Sketch as my daily tool, so I didn't do my due diligence for a while and checked the plugin compatibility.

Will look into it.

**Comment by edclark94** [comment]
Thank you. I can't tell you how much this plugin speeds up my team's workflow. It's a godsend!

**Comment by baptiste-roullin** [comment]
Hi, 

Would you test [this beta version?](https://github.com/baptiste-roullin/data-from-clipboard/releases/download/v0.6.0-beta/data-from-clipboard.sketchplugin.zip) Uninstall the current one, then unzip and double-click on the .sketchplugin file. 

Tested on Sketch v85 et v88: it works with symbols and nested symbols.

**Comment by edclark94** [comment]
It works perfectly. Thank you so much!

From: Baptiste ***@***.***>
Reply to: baptiste-roullin/data-from-clipboard ***@***.***>
Date: Saturday, 21 May 2022 at 10:59
To: baptiste-roullin/data-from-clipboard ***@***.***>
Cc: "Clark, Ed" ***@***.***>, Author ***@***.***>
Subject: Re: [baptiste-roullin/data-from-clipboard] Not working in Sketch 87.1 (Issue #6)


Hi,

Would you test this beta version?<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbaptiste-roullin%2Fdata-from-clipboard%2Freleases%2Fdownload%2Fv0.6.0-beta%2Fdata-from-clipboard.sketchplugin.zip&data=05%7C01%7Ced.clark%40umusic.com%7Cd75e8af72ca741a1dd7508da3b103bf1%7Cbbcb6b2f8c7c4e2486e46c36fed00b78%7C1%7C0%7C637887239615655311%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2FiJ6bDvktJu9Lw5ezXCkWv4JiYPDDd93Djop1Bjd%2FI%3D&reserved=0> Uninstall the current one, then unzip and double-click on the .sketchplugin file.

Tested on Sketch v85 et v88: it works with symbols and nested symbols.

—
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbaptiste-roullin%2Fdata-from-clipboard%2Fissues%2F6%23issuecomment-1133591603&data=05%7C01%7Ced.clark%40umusic.com%7Cd75e8af72ca741a1dd7508da3b103bf1%7Cbbcb6b2f8c7c4e2486e46c36fed00b78%7C1%7C0%7C637887239615665267%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=eYTjXALlDeDaujS6zWJceOIGi1DSdD8Mrx9R%2F92fHbI%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPYCKUSNNHJ3TBQT7ZNPXU3VLCXOJANCNFSM5WEO3L7Q&data=05%7C01%7Ced.clark%40umusic.com%7Cd75e8af72ca741a1dd7508da3b103bf1%7Cbbcb6b2f8c7c4e2486e46c36fed00b78%7C1%7C0%7C637887239615675222%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7SfFzh9yVZoi%2Firsb2NFfWGTN2QHyW1n1NgqmKiSXD4%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

________________________________

**Confidentiality**
The information contained in this e-mail is confidential, may be privileged and is intended solely for the use of the named addressee. Access to this e-mail by any other person is not authorised. If you are not the intended recipient, you should not disclose, copy, distribute, take any action or rely on it and you should please notify the sender by reply. Any opinions expressed are not necessarily those of the company.

We may monitor all incoming and outgoing emails in line with current legislation. We have taken steps to ensure that this email and attachments are free from any virus, but it remains your responsibility to ensure that viruses do not adversely affect you.

**Comment by baptiste-roullin** [comment]
Hurray! Glad to hear it.

And by the way thanks for the compliments.
